apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yvo27tjbm-go
  janus-idp.io/tekton: yvo27tjbm-go
  backstage.io/kubernetes-id: yvo27tjbm-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yvo27tjbm-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
