apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yvo27tjbm-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yvo27tjbm-go 
  name: yvo27tjbm-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yvo27tjbm-go 
